apiVersion: v1
kind: Service
metadata:
  name: udacity-capstone
spec:
  type: LoadBalancer
  selector:
    app: udacity-capstone
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-capstone-deploy
spec:
  selector:
    matchLabels:
      app: udacity-capstone
  replicas: 3
  template:
    metadata:
      labels:
        app: udacity-capstone
    spec:
      containers:
      - name: udacity-capstone-pod
        image: minageorge/udacity-devops-capstone:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 10