apiVersion: v1
kind: Service
metadata:
  name: capstoneBlueGreen
spec:
  type: LoadBalancer
  selector:
    app: capstoneBlueGreen
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstoneBlueGreen
spec:
  selector:
    matchLabels:
      app: capstoneBlueGreen
  replicas: 3
  template:
    metadata:
      labels:
        app: capstoneBlueGreen
    spec:
      containers:
      - name: capstoneBlueGreen
        image: minageorge/udacity-devops-capstone:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 10