Description: >
    Mina George / Udacity-Capstone

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
        
Resources:

  JenkinsSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Jenkins server
      VpcId:
        Fn::ImportValue: 
          !Sub "${EnvironmentName}-VPCID"
     
      SecurityGroupIngress:
     
      - IpProtocol: tcp
        FromPort: 8080
        ToPort: 8080
        CidrIp: 0.0.0.0/0
      
      - CidrIp: 0.0.0.0/0
        IpProtocol: tcp
        FromPort: 22
        ToPort: 22
     
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName} Jenkins Security Group"
    
  Jenkins:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-06f2f779464715dc5
      InstanceType: t3.medium
      KeyName : Udacity-Capstone-jenkins-kp
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      
      SecurityGroupIds:
        - Ref: JenkinsSecGroup
      
      SubnetId:
        Fn::ImportValue: 
          Fn::Sub: "${EnvironmentName}-PUB-SN"

      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Jenkins    
      
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            sudo apt update
            sudo apt install openjdk-8-jdk -y
            wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -
            sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
            sudo apt update
            sudo apt install jenkins -y
            sudo systemctl start jenkins
            sudo apt-get update
            sudo apt install docker.io -y
            sudo apt install tidy -y


